### ISSUE TITLE
yaml.warnings

### ISSUE THREAD

**Issue by cirrusUK** [charmparticle/mpd_what#2]
Upon executing i'd get yaml load errors, and it somehow hindered app from running,
adding 
`yaml.warnings({'YAMLLoadWarning': False})` 
 to the mpd_what file rectifies matters.
    [mpd_what](https://i.imgur.com/vV9Jhro.png)

**Comment by charmparticle** [comment]
The new release should solve this issue, update with pypi, ie:
    pip3 install -U mpd_what (optionally prefixed with 'sudo')

If the YAML really is invalid, mpd_what will now print an error message to stderr.
